@startuml

title FSM Overview

[*] --> STATE_UNREGISTERED

STATE_UNREGISTERED --> STATE_WAITING_FIO : /start

STATE_WAITING_FIO --> STATE_ROLE_DETECTED : пользователь найден
STATE_WAITING_FIO --> STATE_ACCESS_DENIED : пользователь не найден

STATE_ROLE_DETECTED --> STATE_MAIN_MENU

STATE_MAIN_MENU --> STATE_RUNNING_CHECK : /справка

STATE_RUNNING_CHECK --> STATE_SHOW_REPORT

STATE_SHOW_REPORT --> STATE_RUNNING_CHECK : повторный /справка

STATE_MAIN_MENU --> STATE_WAITING_ADMIN_MESSAGE : /ошибка

STATE_WAITING_ADMIN_MESSAGE --> STATE_CONFIRM_ADMIN_MESSAGE

STATE_CONFIRM_ADMIN_MESSAGE --> STATE_SENDING_ADMIN_MESSAGE : Отправить

STATE_SENDING_ADMIN_MESSAGE --> STATE_MAIN_MENU

STATE_ACCESS_DENIED --> STATE_UNREGISTERED : /start

@enduml
