@startuml
title Retry Model

start

:/справка;

:Поиск существующей строки;

if (Строка найдена?) then (да)

:Повторное использование записи;

else (нет)

:Создание новой записи;

endif

:Повторная проверка;

:Обновление snapshot;

:Обновление статуса;

if (Ошибка API?) then (да)

:Retry logic;

endif

:Формирование нового отчета;

stop

@enduml
